package yatzy;

public enum Category {

	ONES, TWOS, THREES, FOURS, FIVES, SIXES, YATZI, PAIR, TWO_PAIRS, SMALL_STRAIGHT, LARGE_STRAIGHT, THREE_OF_A_KIND,
	FOUR_OF_A_KIND, CHANCE, FULL_HOUSE

}
