namespace Yatzy2;

public enum YatzyCategory
{
    CHANCE, YATZY,
    ONES, TWOS, THREES, FOURS, FIVES, SIXES,
    PAIR, THREE_OF_A_KIND, FOUR_OF_A_KIND,
    SMALL_STRAIGHT, LARGE_STRAIGHT,
    TWO_PAIRS, FULL_HOUSE
}